# using POSTGRES

default: &default
  adapter: postgresql
  database: inicio
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: inicio
  pool: 5
  timeout: 5000
  
test:
  adapter: postgresql
  database: inicio
  pool: 5
  timeout: 5000
  
production:
  adapter: postgresql
  database: inicio
  pool: 5
  timeout: 5000